/*
 * splash_screen.c / splash_screen.h  —  EV Dashboard Splash Screen
 *
 * Displays the FJ55 image on boot for SPLASH_DURATION_MS milliseconds,
 * then transitions to the main dashboard.
 *
 * Two modes (choose one in splash_screen.h):
 *
 *   SPLASH_MODE_PARTITION  — loads full 1280×800 RGB565 image from the
 *                            'splash' flash partition. Best quality.
 *                            Requires evj55_splash.bin flashed separately.
 *
 *   SPLASH_MODE_EMBEDDED   — uses the 320×213 C array from evj55_splash_c.h,
 *                            scaled up by LVGL. No extra flash step needed.
 *
 * Integration in main.cpp:
 *
 *   // In ui_task(), before the main loop:
 *   splash_show(g_disp);
 *   vTaskDelay(pdMS_TO_TICKS(SPLASH_DURATION_MS));
 *   splash_hide();
 *   dashboard_ui_create(g_disp);
 */

#pragma once

#include "lvgl.h"
#include "esp_log.h"
#include "esp_partition.h"
#include "esp_heap_caps.h"

// ── Configuration ──────────────────────────────────────────────────────────

// Duration to show splash before transitioning to dashboard
#define SPLASH_DURATION_MS   2500

// Choose ONE of these modes:
#define SPLASH_MODE_EMBEDDED    0   // 320×213 C array, always works
#define SPLASH_MODE_PARTITION   1   // full 1280×800 from flash partition

#ifndef LCD_V_RES
  #define LCD_V_RES 720
#endif

#ifndef SPLASH_MODE
  #define SPLASH_MODE  SPLASH_MODE_EMBEDDED   // safe default
#endif

#if SPLASH_MODE == SPLASH_MODE_EMBEDDED
  #include "evj55_splash_c.h"   // generated by tools/make_splash.py
#endif

static const char *TAG_SPL = "splash";

// ── Private state ──────────────────────────────────────────────────────────
static lv_obj_t         *s_splash_screen  = NULL;
static lv_obj_t         *s_img_obj        = NULL;
#if SPLASH_MODE == SPLASH_MODE_PARTITION
static uint8_t          *s_part_buf       = NULL;
static lv_image_dsc_t    s_part_img_dsc;
#endif

// ── Partition-based loader ─────────────────────────────────────────────────
#if SPLASH_MODE == SPLASH_MODE_PARTITION

static bool splash_load_partition(void)
{
    // Find the 'splash' partition (type=data, subtype=spiffs, label="splash")
    const esp_partition_t *part = esp_partition_find_first(
        ESP_PARTITION_TYPE_DATA, ESP_PARTITION_SUBTYPE_ANY, "splash");

    if (!part) {
        ESP_LOGE(TAG_SPL, "No 'splash' partition found — check partitions_16MB.csv");
        return false;
    }

    const uint32_t expected = 1280 * 800 * 2;  // RGB565
    if (part->size < expected) {
        ESP_LOGE(TAG_SPL, "Splash partition too small: %lu < %lu", part->size, expected);
        return false;
    }

    // Allocate in PSRAM
    s_part_buf = (uint8_t *)heap_caps_malloc(expected,
                                              MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (!s_part_buf) {
        ESP_LOGE(TAG_SPL, "PSRAM alloc failed (%lu bytes)", expected);
        return false;
    }

    ESP_LOGI(TAG_SPL, "Loading splash from partition '%s' @ 0x%08lx...",
             part->label, part->address);

    esp_err_t err = esp_partition_read(part, 0, s_part_buf, expected);
    if (err != ESP_OK) {
        ESP_LOGE(TAG_SPL, "Partition read failed: %s", esp_err_to_name(err));
        heap_caps_free(s_part_buf);
        s_part_buf = NULL;
        return false;
    }

    s_part_img_dsc.header.cf     = LV_COLOR_FORMAT_RGB565;
    s_part_img_dsc.header.flags  = 0;
    s_part_img_dsc.header.w      = 1280;
    s_part_img_dsc.header.h      = 800;
    s_part_img_dsc.header.stride = 1280 * 2;
    s_part_img_dsc.data_size     = expected;
    s_part_img_dsc.data          = s_part_buf;

    ESP_LOGI(TAG_SPL, "Splash image loaded (%lu KB)", expected / 1024);
    return true;
}

#endif  // SPLASH_MODE_PARTITION

// ── Public API ─────────────────────────────────────────────────────────────

/**
 * @brief  Create and display the splash screen.
 *         Call from ui_task() before dashboard_ui_create().
 */
static inline void splash_show(lv_display_t *disp)
{
    s_splash_screen = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(s_splash_screen, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(s_splash_screen, LV_OPA_COVER, 0);
    lv_scr_load(s_splash_screen);           // make it active immediately

    s_img_obj = lv_image_create(s_splash_screen);

#if SPLASH_MODE == SPLASH_MODE_PARTITION
    if (splash_load_partition()) {
        lv_image_set_src(s_img_obj, &s_part_img_dsc);
        lv_obj_set_size(s_img_obj, 1280, 800);
    } else {
        // Partition load failed — show a text fallback
        lv_obj_t *lbl = lv_label_create(s_splash_screen);
        lv_label_set_text(lbl, "EV Dashboard");
        lv_obj_center(lbl);
        return;
    }

#else  // SPLASH_MODE_EMBEDDED
    evj55_splash_img_init();  // populate LVGL 9 image descriptor
    lv_image_set_src(s_img_obj, &evj55_splash_img);
    // Scale the 320×213 thumbnail up to fill the display
    // Scale to fit within display bounds (720px tall display)
    // 320x213 -> fit to 1280 wide: scale=1024 -> 1280x852 (too tall)
    // 320x213 -> fit to 720 tall:  scale=866  -> 1298x720 (slight crop)
    lv_image_set_scale(s_img_obj, 256 * LCD_V_RES / SPLASH_EMBED_H);
#endif

    lv_obj_align(s_img_obj, LV_ALIGN_CENTER, 0, 0);

    // Overlay: subtle branding text at bottom
    lv_obj_t *lbl = lv_label_create(s_splash_screen);
    lv_label_set_text(lbl, "EV DASHBOARD  |  ESP32-P4");
    lv_obj_set_style_text_color(lbl, lv_color_hex(0x334455), 0);
    lv_obj_set_style_text_font(lbl, &lv_font_montserrat_14, 0);
    lv_obj_align(lbl, LV_ALIGN_BOTTOM_MID, 0, -12);

    ESP_LOGI(TAG_SPL, "Splash displayed, showing for %d ms", SPLASH_DURATION_MS);
}

/**
 * @brief  Remove the splash screen and free resources.
 *         Call after the delay, just before dashboard_ui_create().
 */
static inline void splash_hide(void)
{
    if (s_img_obj)       { lv_obj_delete(s_img_obj);       s_img_obj = NULL; }
    if (s_splash_screen) { lv_obj_delete(s_splash_screen); s_splash_screen = NULL; }

#if SPLASH_MODE == SPLASH_MODE_PARTITION
    if (s_part_buf) {
        heap_caps_free(s_part_buf);
        s_part_buf = NULL;
        ESP_LOGI(TAG_SPL, "Splash PSRAM buffer freed");
    }
#endif
}
